POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "David2",
    "age": 18,
    "email": "david@gmail.com",
    "img": "https://cdn.pixabay.com/photo/2016/02/10/21/59/landscape-1192669__340.jpg"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/64aecac4df9ed93eb04cd259 HTTP/1.1

###
PUT  http://localhost:9000/api/users/64aecac4df9ed93eb04cd259 HTTP/1.1
Content-Type: application/json

{
  "name": "cambio",
  "age": 20,
  "email": "david@hotmail.com",
  "img": "https://cdn.pixabay.com/photo/2016/02/10/21/59/landscape-1192669__340.jpg"
}

###
DELETE  http://localhost:9000/api/users/64b0a874d47fa03f72ab8ddc HTTP/1.1
